### ISSUE TITLE
Support for the spartan protocol

### ISSUE THREAD

**Issue by dscp46** [nhanb/mcross#2]
Hi,

I don't know what your stand is on the support of other small net protocols in your project, but please close if this is out of scope of this project.

The [spartan protocol](http://portal.mozz.us/gemini/spartan.mozz.us/specification.gmi) has been developed with a similar rationale as gemini, less the TLS layer and with a lighter protocol specification. On top of that, the content is expected to be served with the existing text/gemini standard, so no significant change is to be expected on the presentation layer.

When compared with other smallnet clients, your project has the advantage to be portable outside of 64 bits platforms, and I thought you might be interested.

Kind regards,

**Comment by nhanb** [comment]
Hi there! I'm aware of spartan but I've mostly lost interest in the smolnet ecosystem as of late. When I do want to browse around, I almost exclusively use <https://portal.mozz.us> these days.

For my own publishing needs, I'm back to minimal html/css making sure it works on [netsurf](https://www.netsurf-browser.org/) and [ladybird](https://ladybird.dev/). I think that's a more viable approach: its backward compatible with what everyone already has - a browser - while giving power users a choice of less power-hungry, more privacy-respecting clients.

Ideally some people would step up and maintain a "smolhtml" standard which is a subset of http/html that rips out the operating-system-wannabe BS, then we can build small browsers for that spec... But honestly, I wouldn't hold my breath.

Edit: All that is to say, I probably won't develop any new feature for McRoss. I'll still fix reported bugs though.
